### ISSUE TITLE
Elevation???

### ISSUE THREAD

**Issue by Jamal-ReachFirst** [hoaphantn7604/react-native-curved-bottom-bar#44]
Unable to add elevation or shadow to bottom tab bar, I don't want to add stroke.

Is there anyway to add shadow to its top side on android.

**Comment by hoaphantn7604** [comment]
Hi @Jamal-ReachFirst ,
I’m working on it.

**Comment by Jamal-ReachFirst** [comment]
> Hi @Jamal-ReachFirst , I’m working on it.

I am using `react-native-drop-shadow` to apply shadow.

Make some changes in `react-native-curved-bottom-bar`: 

```
import DropShadow from "react-native-drop-shadow";

<DropShadow
    style={{
      shadowColor: "#DDDDDD",
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 1,
      shadowRadius: 5,
    }}
  >
      <SVG width={maxWidth} height={height + (type === 'DOWN' ? 0 : 30)}>
        <PATH
          fill={bgColor}
          stroke="#DDDDDD"
          strokeWidth={strokeWidth}
          {...{ d }}
        />
      </SVG>
  </DropShadow>
```

Thanks.

**Comment by hoaphantn7604** [comment]
> > Hi @Jamal-ReachFirst , I’m working on it.
> 
> I am using `react-native-drop-shadow` to apply shadow.
> 
> Make some changes in `react-native-curved-bottom-bar`:
> 
> ```
> import DropShadow from "react-native-drop-shadow";
> 
> <DropShadow
>     style={{
>       shadowColor: "#DDDDDD",
>       shadowOffset: {
>         width: 0,
>         height: 0,
>       },
>       shadowOpacity: 1,
>       shadowRadius: 5,
>     }}
>   >
>       <SVG width={maxWidth} height={height + (type === 'DOWN' ? 0 : 30)}>
>         <PATH
>           fill={bgColor}
>           stroke="#DDDDDD"
>           strokeWidth={strokeWidth}
>           {...{ d }}
>         />
>       </SVG>
>   </DropShadow>
> ```
> 
> Thanks.

Thank you very helpful.

**Comment by hoaphantn7604** [comment]
hi All, Top shadow do not working on Android. I'm find solutions.

**Comment by Jamal-ReachFirst** [comment]
> hi All, Top shadow do not working on Android. I'm find solutions.

What is the solution, when are you going to push it to this package?

**Comment by BillDelvin** [comment]
> hi All, Top shadow do not working on Android. I'm find solutions.

can I know what is the solution ?

**Comment by Jamal-ReachFirst** [comment]
> react-native-drop-shadow

`react-native-drop-shadow` use this

**Comment by BillDelvin** [comment]
did you have example code for reference ?

**Comment by Jamal-ReachFirst** [comment]
> did you have example code for reference ?

As shown [here](https://github.com/hoaphantn7604/react-native-curved-bottom-bar/issues/44#issuecomment-1305073686)

```
import DropShadow from "react-native-drop-shadow";

<DropShadow
    style={{
      shadowColor: "#DDDDDD",
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 1,
      shadowRadius: 5,
    }}
  >
      // child component
  </DropShadow>
```

**Comment by hoaphantn7604** [comment]
hi All,
This issue is resolved. Please install version 3.1.0 Later re-build app.
add shadow ([9fb40da](https://github.com/hoaphantn7604/react-native-curved-bottom-bar/commit/9fb40da148fa9bee368b9a7796b0f677f0fba58b))

**Comment by Jamal-ReachFirst** [comment]
> hi All, This issue is resolved. Please install version 3.1.0 Later re-build app. add shadow ([9fb40da](https://github.com/hoaphantn7604/react-native-curved-bottom-bar/commit/9fb40da148fa9bee368b9a7796b0f677f0fba58b))

@hoaphantn7604 Thanks for your efforts and hard work, the shadow is working now but I am unable to change the shadow properties (no method/prop provided to override the existing shadow style).

I am manually changing the shadow style inside `react-native-curved-bottom-bar/src/CurvedBottomBar/Components/BottomBarView/styles.ts `

```
shadow: {
    shadowColor: '#DDDDDD',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 1,
    shadowRadius: 5,
  },
```

Can you please provide a method/prop to override this style??

**Comment by hoaphantn7604** [comment]
> > hi All, This issue is resolved. Please install version 3.1.0 Later re-build app. add shadow ([9fb40da](https://github.com/hoaphantn7604/react-native-curved-bottom-bar/commit/9fb40da148fa9bee368b9a7796b0f677f0fba58b))
> 
> @hoaphantn7604 Thanks for your efforts and hard work, the shadow is working now but I am unable to change the shadow properties (no method/prop provided to override the existing shadow style).
> 
> I am manually changing the shadow style inside `react-native-curved-bottom-bar/src/CurvedBottomBar/Components/BottomBarView/styles.ts `
> 
> ```
> shadow: {
>     shadowColor: '#DDDDDD',
>     shadowOffset: {
>       width: 0,
>       height: 0,
>     },
>     shadowOpacity: 1,
>     shadowRadius: 5,
>   },
> ```
> 
> Can you please provide a method/prop to override this style??

This issue is resolved. Install new version. You can use shadowStyle props.

**Comment by ecartersupport** [comment]
It's not working in Android. It's not showing any shadow

**Comment by black1ava** [comment]
FYI, I use version 3.5.0 and shadow is still not working and Android.

**Comment by princetoad1995** [comment]
+1
any ideas for display shadow on Android?

<img width="344" height="149" alt="Image" src="https://github.com/user-attachments/assets/3df0f595-f1bc-4735-aaf4-2537da4457ea" />
